steps:
  - name: Setup ngrok
    run: |
      # ngrok 설치 (예시)
      curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
      echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
      sudo apt update
      sudo apt install ngrok

      # ngrok authtoken 설정 (반드시 YOUR_NGROK_AUTH_TOKEN을 실제 토큰으로 교체)
      # secrets.NGROK_AUTH_TOKEN을 사용하여 민감한 정보를 안전하게 관리하는 것이 좋습니다.
      ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

  - name: Run Python server
    run: |
      python run_server.py &
      sleep 5 # Wait for the server to start

  - name: Start ngrok in background
    run: |
      # ngrok을 백그라운드에서 실행하고, 에러가 나도 워크플로우가 멈추지 않도록 '&'를 사용
      ngrok http 8000 & # 예시로 8000 포트를 터널링
      echo "ngrok started in background."
    # 워크플로우가 종료될 때 ngrok 프로세스가 자동으로 종료되도록 하는 추가 설정이 필요할 수 있습니다.

  - name: Wait for ngrok tunnel to be ready
    run: |
      MAX_RETRIES=10
      RETRY_INTERVAL=5 # seconds
      for i in $(seq 1 $MAX_RETRIES); do
        echo "Attempt $i/$MAX_RETRIES: Checking ngrok API..."
        # curl -sS는 오류 발생 시에도 메시지를 표시하고, -f는 HTTP 오류 시 종료
        # grep -q "tunnels"는 응답에 "tunnels" 문자열이 있는지 확인
        if curl -sS -f http://127.0.0.1:4040/api/tunnels | grep -q "tunnels"; then
          echo "ngrok API is ready!"
          break
        else
          echo "ngrok API not ready yet. Waiting for $RETRY_INTERVAL seconds..."
          sleep $RETRY_INTERVAL
        fi
        if [ $i -eq $MAX_RETRIES ]; then
          echo "Error: ngrok API did not become ready after $MAX_RETRIES attempts."
          exit 1
        fi
      done
      # ngrok API에서 터널 정보를 가져와서 변수에 저장 (예시)
      PUBLIC_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
      echo "ngrok Public URL: $PUBLIC_URL"
      echo "PUBLIC_URL=$PUBLIC_URL" >> $GITHUB_ENV # 다음 스텝에서 사용할 수 있도록 환경 변수에 저장
    env:
      # jq가 설치되어 있지 않다면 설치하는 단계가 필요할 수 있습니다.
      # sudo apt install jq
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }} # NGROK_AUTH_TOKEN 환경 변수 사용 예시